package generated;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ExecutionException;
import recaf.async.AsyncExtension;
 
public class TestAsyncWithAwait {
   private static recaf AsyncExtension<Integer> alg = new AsyncExtension<Integer>();

    recaf CompletableFuture<Integer> op() {
    	if (1 < 2) {
       		await Integer x = secondOp();
       		return x;
     	}
     	return 41;
  	} 
  	
  	recaf CompletableFuture<Integer> secondOp() {
    	if (1 < 2) { 	
       		return 42;
     	}
     	return 41;
  	}
  	
  	public static void main(String[] args) throws InterruptedException, ExecutionException{
  		Integer answer = new TestAsyncWithAwait().op().get();
  		
  		System.out.println(answer);
  	}
}